const mongoose = require('mongoose');
const { Schema } = mongoose;

const transactionSchema = new Schema({
  user: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true
  }, // Reference to the User who made the purchase.
  tx_ref: {
    type: String,
    required: true,
    unique: true
  }, // A unique reference string for the transaction (generated by us).
  transaction_id: {
    type: String
  }, // Transaction ID from Flutterwave (to be filled after verification by the transaction in flutterwaveWebhook handler in paymentController).
  amount: {
    type: Number,
    required: true
  }, // Amount paid in the transaction 
  currency: {
    type: String,
    default: 'USD'
  }, // Currency of the transaction Defaults to 'USD' (since packages are in dollars).
  coins: {
    type: Number,
    required: true
  }, // Number of coins purchased in this transaction.
  status: {
    type: String,
    enum: ['initiated', 'processing', 'successful', 'failed'],
    default: 'initiated'
  } // Enum for 'initiated', 'successful', 'failed' to track the payment lifecycle.
}, { timestamps: true });

module.exports = mongoose.model('Transaction', transactionSchema);